version: "3"

services: 
  backend:
    build: .
      # context: ./backend-test
      # dockerfile: Dockerfile
    #We use proxy, so we don't want to access the backend on port 9000, just on 8000
    #ports:
    #  - "9000:9000"
    restart: unless-stopped
    volumes:
      - ./node_modules:/usr/app/node_modules
  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf